apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-efcq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sbudhwar-1-tenant/devfile-sample-1/devfile-sample-efcq@sha256:870173356d28e675cc88040b542f4829c5af1b274b834b708de908ed374b52f9
        name: my-nodejs
        resources: {}
status: {}
